services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adonis-app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3333:3333'
    depends_on:
      - mariadb
    environment:
      NODE_ENV: development
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: challenge_adonis
      DB_USERNAME: root
      DB_PASSWORD: password
    networks:
      - app-network
    command: >
      sh -c "node ace migration:run && npm run dev"

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: challenge_adonis
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge
